import './globals.css'

import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'

// Define your fonts
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const montserratMono = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat-mono',
})


export const metadata: Metadata = {
  title: 'New Day',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserratMono.variable} antialiased`}>{children}</body>
    </html>
  )
}
